// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xo_xUDMuKM-crd_LZQX6iayAA4fPgU4',
    appId: '1:747299572839:web:7bb8fc1876a5203def58c2',
    messagingSenderId: '747299572839',
    projectId: 'tbank-817bc',
    authDomain: 'tbank-817bc.firebaseapp.com',
    storageBucket: 'tbank-817bc.firebasestorage.app',
    measurementId: 'G-CZBKE6BPFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvifN6qEX6Hbpygfs9y3rdmxCK6PU-5wo',
    appId: '1:747299572839:android:c58a5dfc23873355ef58c2',
    messagingSenderId: '747299572839',
    projectId: 'tbank-817bc',
    storageBucket: 'tbank-817bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zPsTAmbNwkJRn5115rogiLfyNPWIDfY',
    appId: '1:747299572839:ios:1a2b27e2eefb1773ef58c2',
    messagingSenderId: '747299572839',
    projectId: 'tbank-817bc',
    storageBucket: 'tbank-817bc.firebasestorage.app',
    iosBundleId: 'com.example.tbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zPsTAmbNwkJRn5115rogiLfyNPWIDfY',
    appId: '1:747299572839:ios:1a2b27e2eefb1773ef58c2',
    messagingSenderId: '747299572839',
    projectId: 'tbank-817bc',
    storageBucket: 'tbank-817bc.firebasestorage.app',
    iosBundleId: 'com.example.tbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4xo_xUDMuKM-crd_LZQX6iayAA4fPgU4',
    appId: '1:747299572839:web:cd71aa622df53bb5ef58c2',
    messagingSenderId: '747299572839',
    projectId: 'tbank-817bc',
    authDomain: 'tbank-817bc.firebaseapp.com',
    storageBucket: 'tbank-817bc.firebasestorage.app',
    measurementId: 'G-V0M04MJ1W1',
  );
}
